export const turnsTypes = {
    ADD_TURN: 'ADD_TURN',
    REMOVE_TURN: 'REMOVE_TURN',
    FILTER_TURN: 'FILTER_TURN',
    GET_TURNS: 'GET_TURNS',
    NO_TURNS_RETRIEVED:'NO_TURNS_RETRIEVED',
    SELECTED_DATE:'SELECTED_DATE',
    REFRESH_DATE:'REFRESH_DATE'
};